name: Pull Request
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      # Write permission is required for Dependabot to commit changes by pint and eslint.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run lint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix code style
          commit_options: "--no-verify"
